services:
  sonarqube:
    image: sonarqube:community
    restart: unless-stopped
    ports:
      - '9000:9000'
    networks:
      - internal
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL

  sonar-scanner-cli:
    image: sonarsource/sonar-scanner-cli:12
    restart: unless-stopped
    environment:
      SONAR_HOST_URL: 'http://sonarqube:9000'
      SONAR_TOKEN: 'sqp_4787a37aa05b72b2c3fe75c1342f4758fd132357'
    volumes:
      - ./:/srv/gitlab-ci-validator
    command: ['sleep', 'infinity']
    networks:
      - internal
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL

networks:
  internal:
    driver: bridge
